# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32dd83e39a2bf768fb88d63a0d81916f26eefef4a867a6d2ba2bd3725b5037b315fa975ce4a6f7e22b231f35d7c397a14bdd880284988a88e74564d830745c4

test:
  secret_key_base: 1115a163421cbce1f56a7a8863f365c6578fffa8f9d39a6a448a2f6f430ff7adca17ced510388c0c816c2cb872c6c797d0214fa95585c02d6250bdfbafbf69b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
